### ISSUE TITLE
Error: Cannot find module 'nodexchange'

### ISSUE THREAD

**Issue by tolik93** [DataHiveDJW/nodexchange#3]
Hello everybody,

i am trying to load your module into my test project, but it throw an error.
I installed nodexchange module with npm 5.0.0 
What did i wrong? 

```
const http = require('http');`

const lb = require('nodexchange');

const options = [
    {
        hostname: '127.0.0.1',
        port: 3000,
    },
    {
        hostname: '127.0.0.1',
        port: 4000,
    },
    {
        hostname: '127.0.0.1',
        port: 5000,
    },
]

const rb = lb.deploy('rp', options);

const server = http.createServer((req, res)=> {
    rb.init(req, res);
res.end('Hello');
}).listen(8080, ()=>{
    console.log('Server is listening on port 8080');
});

```

Thank you

**Comment by dmckirnan** [comment]
Did you NPM install the 'nodexchange' module? I see you have it required in, yet it will need to be NPM installed directly

**Comment by tolik93** [comment]
Yes i did

 

Von: dmckirnan [mailto:notifications@github.com] 
Gesendet: Freitag, 26. Mai 2017 21:56
An: DataHiveDJW/nodexchange <nodexchange@noreply.github.com>
Cc: tolik93 <anatolij.novosolov@student.fh-kiel.de>; Author <author@noreply.github.com>
Betreff: Re: [DataHiveDJW/nodexchange] Error: Cannot find module 'nodexchange' (#3)

 

Did you NPM install the 'nodexchange' module? I see you have it required in, yet it will need to be NPM installed directly

**Comment by DougCal** [comment]
I went ahead and copy+pasted your code and it seems to be working fine.  Your code is good, but something else is happening that doesn't involve your code.

EDIT: On your reverse-proxy, you're trying to make a write when the reverse-proxy is only to route requests to your app servers (e.g. 127.0.0.1:300).  The only part of your test project that should be writing to your browser is your app server and not the reverse proxy.  Your reverse-proxy seems to be what is sending the error on my end.  Try that out and let us know how it goes.

**Comment by dmckirnan** [comment]
It's working on our side. I'll get back to you ASAP

**Comment by tolik93** [comment]
@DougCal 
![image](https://cloud.githubusercontent.com/assets/17907942/26511200/38dda058-4261-11e7-97f2-a0a98ca9d7b4.png)

I am not able to start my proxy-server, cause there is an error.

**Comment by dmckirnan** [comment]
@tolik93 

We've located and resolved the issue. Please pull down the latest version from NPM. We really appreciate your input and helping us locate the bug. The new version should be "1.6.1".

Thank you again,

NodeXchange

**Comment by tolik93** [comment]
@dmckirnan Thx it works
